[package]
name = "dbcrack"
version = "0.1.5"
authors = ["Mason Sipe <m-sipe@protonmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
rusqlite = {version = "0.24.0", features = ["bundled"]}
md-5 = "0.9.1"
hex = "0.4.2"