[package]
name = "dbcrack"
version = "3.0.0"
authors = ["Mason Sipe <m-sipe@protonmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
csv = "1.1"
serde = { version = "1", features = ["derive"] }